### ISSUE TITLE
How to key a key?

### ISSUE THREAD

**Issue by melroy89** [wvengen/shopscraper-api#1]
I like to know how to get a key from AH API?

**Comment by wvengen** [comment]
For this project you don't need one. Having the user's credentials is enough.

Recently AH has been been [publishing a bit more](https://frahmework.ah.nl/ah/doh) about their API, for which you do need a key. In the long run, this project may become obsolete by that.

**Comment by melroy89** [comment]
Hier staat dat je deze kan aanvragen, geen idee waar helaas:

![personal_key](https://cloud.githubusercontent.com/assets/628926/11362947/2c7800ae-9297-11e5-96de-196fd0c15ebb.png)

**Comment by wvengen** [comment]
Was probably part of the hackathon. I suppose they'll be opening it up more in due time.
