### ISSUE TITLE
Legal?

### ISSUE THREAD

**Issue by PetervdWal** [wvengen/shopscraper-api#4]
Hi Wvengen, 

Just wondering if this type of scraping is legal for commercial use (e.g. an app or website)

**Comment by wvengen** [comment]
For internal use, this should be no problem, but [IANAL](https://en.wikipedia.org/wiki/IANAL). If you re-publish the data, that has different considerations. But as this acts as a proxy, where the service is like a translator from HTML to a JSON-based API, it is different from creating a copy in a database, and would be similar to Google Translate.

It really depends on your use-case.
